image: rust:latest
stages:
  - build
  - cleanup
run-build:
  stage: build
  image: rust:latest
  script:
    - cargo build --offline
release:
  stage: build
  image: rust:latest
  script:
    - cargo build --release --offline
    - strip target/release/pmetrics
  artifacts:
    paths:
      - target/release/pmetrics
  only:
    - main
