image: rust:latest
stages:
  - build
run-build:
  stage: build
  image: rust:latest
  script:
    - cargo build
release:
  stage: build
  image: rust:latest
  script:
    - cargo build --release
    - strip target/release/pmetrics
  artifacts:
    paths:
      - target/release/pmetrics
  only:
    - main
