apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    annotations:
    name: pmetrics
spec:
    maxReplicas: 10
    minReplicas: 5
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: pmetrics
    targetCPUUtilizationPercentage: 60
